### ISSUE TITLE
Restoring wallet from seed words fails

### ISSUE THREAD

**Issue by altbieralt** [project-serum/spl-token-wallet#122]
I'm not sure if this is particular to my wallet, but when restoring it goes to the page and loads fine all my balance and tokens, after that redirects back to a blank page.

Here's the console error:

[www.sollet.io-1614613716008.log](https://github.com/project-serum/spl-token-wallet/files/6062842/www.sollet.io-1614613716008.log)

This happens on both Chrome and Safari.

**Comment by camzilla1050** [comment]
Yes dude me too

**Comment by armaniferrante** [comment]
Should be addressed by https://github.com/project-serum/spl-token-wallet/commit/bda5c4c32327ee0583faf4633a9d8e6f3f37133d. Please reopen if you have any more trouble.

**Comment by altbieralt** [comment]
thanks, worked here!

**Comment by camzilla1050** [comment]
Now i have addresses but i can't recover the mine with funds

**Comment by ahmetdgd** [comment]
> Now i have Derivable Accounts but i can't recover the mine with funds

I have the same problem. Could you solve that ?

**Comment by galtej** [comment]
> Now i have Derivable Accounts but i can't recover the mine with funds

Same here. 

I create a sollet wallet I added an extra account in addition to the main account and I send a little amount to this added account in order to test it.

I also wanted to test the restoring procedure before doing anything more.

I am able to proceed and a lists of multiple Derivable Accounts appears, in the first place appears the the main account and in the second the added one with the funds. Then I restore but only the main account is restored.

**Comment by Berhan91** [comment]
Same issue. Did anyone found the solution for this?

> > Now i have Derivable Accounts but i can't recover the mine with funds
> 
> Same here.
> 
> I create a sollet wallet I added an extra account in addition to the main account and I send a little amount to this added account in order to test it.
> 
> I also wanted to test the restoring procedure before doing anything more.
> 
> I am able to proceed and a lists of multiple Derivable Accounts appears, in the first place appears the the main account and in the second the added one with the funds. Then I restore but only the main account is restored.
