### ISSUE TITLE
Unable to restore Solana wallet 

### ISSUE THREAD

**Issue by oluwatobiloba024** [project-serum/spl-token-wallet#204]
I'm unable to restore my Solana wallet even after putting in my 24 seed words. The Grey Next button isn't activated, I'm unable to click on the NEXT button. I need a way out

**Comment by Mathieu44840** [comment]
Hello, I have the same issue here, impossible to click on the Next button

**Comment by TrongNguyen1198** [comment]
Hello, I have the same issue here, impossible to click on the Next button

**Comment by mateoprix** [comment]
same here, cannot click on next. :/

**Comment by aMp37** [comment]
Hello. I have same problem. The "next" button is greyed out when I enter 24 seed words phrase.

**Comment by mid-therm** [comment]
I have same issue, need help.

**Comment by Maniekcebula007** [comment]
Unable to restore Solana wallet. Please help

**Comment by armaniferrante** [comment]
The next button is explicitly greyed out when the mnemonic is incorrect. Everytime i've seen this it's because of a typo, mispelling, the input just being wrong. 

If you want to convince yourself this is not a sollet problem, enter the same seed into a different wallet, with the same derivation path, and you will either not be able to or the address reported will be incorrect. If you successfully do this, i.e. use the mnemonic succesfully in another wallet *and* get the expected address *and* you cannot do so in sollet, please re-open. 

For further assistance, please join the discord channel.
