### ISSUE TITLE
Restoring my sollet wallet

### ISSUE THREAD

**Issue by Bleweye** [project-serum/spl-token-wallet#277]
My antivirus reset my sollet wallet (but not my other wallets) and I'm not able to get into my wallet.  When I try to restore wallet it submits 3 option for derivable accounts: m/44'/501'/0' and m/44'/501'/0'/0' and m/501'/0'/0/0 (deprecated) non of them has my previous funded address. Please help

**Comment by Kubrakahraman775** [comment]
I can't find my solanium wallet, I opened a lot of addresses, none of them have solanium please help

**Comment by calmcooley** [comment]
I am having the same exact issues here. I can't access my sollet.io wallet sadly. Please help

**Comment by armaniferrante** [comment]
To prove whether this is or is not a sollet bug, try restoring your seed with another wallet  (like phantom wallet) and seeing if you get the same address. Key derivation is deterministic so if you use the same seed and derivation path in different wallets you'll get the same address. If this is the case, then it's working as expected. Otherwise, there may be a bug.

For further assistance, please join the discord https://discord.gg/HptFvWYm.

Closing as this is very unlikely to be a sollet issue. However, if you can restore your address in phantom or another wallet and cannot do so in sollet, please re-open.
