### ISSUE TITLE
"ACCOUNT" menu items "Add" and "Delete" are not symmetrical and could lead to a loss of accounts

### ISSUE THREAD

**Issue by jackcmay** [project-serum/spl-token-wallet#69]
The `ACCOUNT` menu lets a user add a single account via `Add Account`, but the `Delete Account` doesn't just delete the selected account, it deletes all accounts, scary!

1. Is there a way to delete a single account?
2. If `Delete Account` deletes all accounts, maybe it should be called `Delete All Accounts`

**Comment by luciotato** [comment]
+1
I've just deleted the wallet trying to delete a single account

**Comment by armaniferrante** [comment]
Addressed by https://github.com/project-serum/spl-token-wallet/pull/120.

* Renames "Delete Account" to "Delete Mnemonic".
* Adds an additional text field to the dialog, requiring the user to type in "delete" before the delete button is enabled.

If this isn't clear still, please re-open.

Single account deletion is not implemented. Tracking that issue here https://github.com/project-serum/spl-token-wallet/issues/121.

**Comment by luciotato** [comment]
how about "delete wallet"? what is the user deleting exactly? 
because it feels a lot like deleting the wallet
