### ISSUE TITLE
When full ledger support?

### ISSUE THREAD

**Issue by 0xTimepunk** [project-serum/spl-token-wallet#97]
I click Import Hardware Wallet, select a ledger and nothing happens. I still view the account created with the generated seed.

Is Sollet ready to work with Ledger?

**Comment by armaniferrante** [comment]
I think it only works with macOS at the moment.

**Comment by j-mars** [comment]
> I think it only works with macOS at the moment.

Okay. I am on Windows 10 using Chrome maybe that's the reason. When should I expect it work with this setup?

**Comment by armaniferrante** [comment]
I don't think any of the sollet developers have access to a windows machine, so it's not immediately on our roadmap. PRs are welcome, though.

**Comment by j-mars** [comment]
It is becoming an increasingly higher barrier of entry for ledger users on Windows to be able to access Solana dApps because they do not have a wallet solution (as seen on Raydium.io)

Just letting you know that maybe you could coordinate the team to have this feature soon? Many are needing it.

But of course, no pressure, your decision. Solflare.com seems to be an alternative fow now.

Thanks
